apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kube-green-staging

# Base configuration
resources:
  - ../../base
  - staging-specific-sleepinfos.yaml
  - staging-monitoring.yaml

# Staging-specific labels
commonLabels:
  environment: staging
  app.kubernetes.io/instance: kube-green-staging

# Staging-specific annotations
commonAnnotations:
  environment: staging
  deployment.version: v1.0.0
  cost-optimization.enabled: "true"

# Namespace override for staging
namespace: kube-green-system

# Staging-specific image tags
images:
  - name: kubegreen/kube-green
    newTag: v0.5.1

# Staging-specific configuration patches
patchesStrategicMerge:
  - staging-deployment-patch.yaml
  - staging-config-patch.yaml

# JSON patches for staging-specific modifications
patchesJson6902:
  - target:
      version: v1
      kind: Deployment
      name: kube-green-controller-manager
    path: staging-deployment-patches.yaml

# Staging-specific ConfigMap generators
configMapGenerator:
  - name: kube-green-staging-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=info
      - ENABLE_WEBHOOKS=true
      - METRICS_ADDR=:8080
      - HEALTH_PROBE_ADDR=:8081
      - SLACK_CHANNEL=#k8s-optimization-staging
      - COST_TRACKING_ENABLED=true
      - MANUAL_OVERRIDE_ENABLED=true
      - NOTIFICATION_LEVEL=detailed
    files:
      - staging-schedule.yaml
      - staging-policies.json

# Staging-specific Secret generators
secretGenerator:
  - name: kube-green-staging-secrets
    env: staging.env
    type: Opaque

# Resource name prefixes for staging
namePrefix: staging-

# Resource name suffixes
nameSuffix: -v1

# Staging-specific replica counts
replicas:
  - name: kube-green-controller-manager
    count: 2

# Staging-specific resource requirements
replacements:
  - source:
      kind: ConfigMap
      name: kube-green-staging-config
      fieldPath: data.ENVIRONMENT
    targets:
      - select:
          kind: Deployment
          name: kube-green-controller-manager
        fieldPaths:
          - spec.template.spec.containers.[name=manager].env.[name=ENVIRONMENT].value
  - source:
      kind: ConfigMap
      name: kube-green-staging-config
      fieldPath: data.SLACK_CHANNEL
    targets:
      - select:
          kind: SleepInfo
        fieldPaths:
          - metadata.annotations.[kube-green.dev/slack-channel]
